### PR TITLE
Add armhf and arm64 arch_suffix for wxWidgets build

### LINKED ISSUE #1340: Cmake build failing on aarch64 Ubuntu
**Describe the bug**
```
wxwidgets/3.1.3.1-audacity: ERROR: while executing system_requirements(): local variable 'arch_suffix' referenced before assignment
ERROR: Error in system requirements
CMake Error at cmake-proxies/cmake-modules/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:233 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:254 (_conan_install)
  CMakeLists.txt:509 (resolve_conan_dependencies)
```
**To Reproduce**
```
cmake -G "Unix Makefiles" -Daudacity_use_ffmpeg=loaded ..

```
**Expected behavior**
Creation of Makefiles

**Additional information:**
 - OS: Ubuntu 18.04 aarch64
 - Version: git Master branch

### LINKED ISSUE #1390: build failure in Raspberry Pi OS
**Describe the bug**
Raspberry OS is an Linux variant, so I follow the Linux section in BUILDING.md
Error occurs in step 2: cmake -G "Unix Makefiles" -Daudacity_use_ffmpeg=loaded ../audacity

ERROR: Not able to automatically detect '/usr/bin/cc' version
ERROR: Unable to find a working compiler
WARN: wxwidgets/3.1.3.1-audacity: requirement expat/2.2.9 overridden by your conanfile to expat/2.2.9@audacity/stable 
wxwidgets/3.1.3.1-audacity: ERROR: while executing system_requirements(): local variable 'arch_suffix' referenced before assignment
ERROR: Error in system requirements
CMake Error at cmake-proxies/cmake-modules/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:233 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:254 (_conan_install)
  CMakeLists.txt:509 (resolve_conan_dependencies)

**Additional information (please complete the following information):**
 - OS: Raspberry OS
 - Version: Audacity 3.0.3
[CMakeError.log](https://github.com/audacity/audacity/files/6911111/CMakeError.log)
[CMakeOutput.log](https://github.com/audacity/audacity/files/6911112/CMakeOutput.log)

 
**Additional context**
My gcc version meets requirement.

### PR DESCRIPTION
**Pull request by lucyllewy**
Fixes audacity/audacity#1390
Fixes audacity/audacity#1340

### CODE REVIEW

**Comment by crsib** [comment]
What a great PR! Can you please add `3.1.3.2-audacity` to config.yml, so I can safely upload the recipe?

**Comment by lucyllewy** [comment]
done. I think I did that bit right....?

**Comment by crsib** [comment]
Awesome, thank you!

**Comment by crsib** [comment]
I have pushed 3.1.3.2 to Artifactory, I will update Audacity soon

Can you please check that changing the wxWidgets version for you? https://github.com/audacity/audacity/blob/master/cmake-proxies/CMakeLists.txt#L54

**Comment by lucyllewy** [comment]
I've just successfully built amd64 and arm64, but armhf failed due to an issue in thumb instructions included in libmad. I've filed a pr at audacity/libmad#2, which you've already merged to fix that issue.

**Comment by crsib** [comment]
I will update recipe for libmad tomorrow I guess, really have to go now

**Pull request merged**
